---
apiVersion: v1
kind: Secret
metadata:
  name: webhooks-https-certs
  namespace: d8-{{ .Chart.Name }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.csiCeph.internal.customWebhookCert.ca }}
  tls.crt: {{ .Values.csiCeph.internal.customWebhookCert.crt }}
  tls.key: {{ .Values.csiCeph.internal.customWebhookCert.key }}
