---
apiVersion: v1
kind: Service
metadata:
  name: webhooks
  namespace: d8-{{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: http
  selector:
    app: webhooks