- name: kubernetes.replicated.storage_class
  rules:
    - alert: StorageClassNewCephClusterConnectionCreated
      expr: sum(kube_storageclass_info{provisioner=~"cephfs.csi.ceph.com|rbd.csi.ceph.com"} * on(storageclass) group_left() kube_storageclass_labels{storage.deckhouse.io/migratedFromCephClusterAuthenticationWarning="true"}) > 0
      for: 5m
      labels:
        severity_level: "6"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_drbd_device_health: "D8CsiCephStorageClassProblem,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_drbd_device_health: "D8CsiCephStorageClassProblem,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: There are new Ceph cluster connections custom resources created for storage classes
        description: |
          During the migration process, several CephClusterAuthentication resources were discovered. For each of them, a separate CephClusterConnection resource was created. 
          This does not require any additional actions, but you may need to make changes to your IaC repositories. 
          If no changes are needed or you have already made the necessary adjustments, remove the label storage.deckhouse.io/migratedFromCephClusterAuthenticationWarning from the CephStorageClass resources:

          `kubectl label storageclass --all storage.deckhouse.io/migratedFromCephClusterAuthenticationWarning-`
          
    - alert: StorageClassCephClusterAuthenticationNotMigrated
      expr: sum(kube_storageclass_info{provisioner=~"cephfs.csi.ceph.com|rbd.csi.ceph.com"} * on(storageclass) group_left() kube_storageclass_labels{storage.deckhouse.io/migratedFromCephClusterAuthentication="false"}) > 0
      for: 5m
      labels:
        severity_level: "4"
        tier: cluster
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__d8_drbd_device_health: "D8CsiCephStorageClassProblem,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__d8_drbd_device_health: "D8CsiCephStorageClassProblem,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: There are non-migrated Ceph cluster authentication custom resources for storage classes
        description: |
          Migration from CephClusterAuthentication resources in some Storage Classes failed. You can get a list of StorageClasses with issues using the following command:

          `kubectl get storageclasses.storage.k8s.io -l storage.deckhouse.io/migratedFromCephClusterAuthentication=false`

          Check the Deckhouse logs and address the existing issues.
