apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cephstorageclasses.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: csi-ceph
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    plural: cephstorageclasses
    singular: cephstorageclass
    kind: CephStorageClass
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            CephStorageClass is a Kubernetes Custom Resource that defines a configuration for a Kubernetes Storage class.
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - clusterName
                - allowVolumeExpansion
                - pool
                - reclaimPolicy
                - type
              oneOf:
                - required:
                    - rbd
                - required:
                    - cephfs
              properties:
                clusterName:
                  description: |
                    Name of the CephCluster custom resource.
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  minLength: 1
                allowVolumeExpansion:
                  description: |
                    AllowVolumeExpansion is a flag that enables or disables volume expansion for the storage class.
                  type: boolean
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                pool:
                  description: |
                    Name of the Ceph pool.
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  minLength: 1
                reclaimPolicy:
                  description: |
                    The storage class's reclaim policy. Might be:
                    - Delete (If the Persistent Volume Claim is deleted, deletes the Persistent Volume and its associated storage as well)
                    - Retain (If the Persistent Volume Claim is deleted, remains the Persistent Volume and its associated storage)
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  enum:
                    - Delete
                    - Retain
                type:
                  description: |
                    The type of the storage class. Might be:
                    - cephfs (CephFS)
                    - rbd (Rados Block Device)
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  enum:
                    - cephfs
                    - rbd
                cephfs:
                  type: object
                  description: |
                    CephFS specific parameters.
                  required:
                    - fsName
                  properties:
                    fsName:
                      description: |
                        Name of the CephFS file system.
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      minLength: 1
                rbd:
                  type: object
                  description: |
                    Rados Block Device specific parameters.
                  required:
                    - defaultFSType
                  properties:
                    defaultFSType:
                      description: |
                        Default file system type for the Rados Block Device.
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      minLength: 1
                mountOptions:
                  description: |
                    Mount options.
                  type: array
                  items:
                    type: string
            status:
              type: object
              description: |
                Displays current information about the Storage Class.
              properties:
                phase:
                  type: string
                  description: |
                    The Storage class current state. Might be: 
                    - Failed (if the controller received incorrect resource configuration or some errors occurred during the operation)
                    - Create (if everything went fine)
                  enum:
                    - Failed
                    - Created
                reason:
                  type: string
                  description: |
                    Additional information about the current state of the Storage Class.
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .status.reason
          name: Reason
          type: string
          priority: 1
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          description: The age of this resource
