apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:manage:csi-ceph:viewer
  labels:
    heritage: deckhouse
    module: csi-ceph
    rbac.deckhouse.io/use-role: viewer
    rbac.deckhouse.io/kind: manage
    rbac.deckhouse.io/level: subsystem
    rbac.deckhouse.io/subsystem: csi-ceph
    rbac.deckhouse.io/aggregate-to-csi-ceph-as: manager
    rbac.deckhouse.io/aggregate-to-all-as: viewer
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.deckhouse.io/kind: manage
        rbac.deckhouse.io/aggregate-to-csi-ceph-as: viewer
rules: []
